/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAiAnalystRouteImport } from './routes/_app/ai-analyst'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppClubsRouteImport } from './routes/_app/clubs'
import { Route as AppMarketRouteImport } from './routes/_app/market'
import { Route as AppMyClubRouteImport } from './routes/_app/my-club'
import { Route as AppPlayersRouteImport } from './routes/_app/players'
import { Route as AppRumoursRouteImport } from './routes/_app/rumours'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppWatchlistRouteImport } from './routes/_app/watchlist'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAnalystRoute = AppAiAnalystRouteImport.update({
  id: '/ai-analyst',
  path: '/ai-analyst',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsRoute = AppClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClubRoute = AppMyClubRouteImport.update({
  id: '/my-club',
  path: '/my-club',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayersRoute = AppPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AppRoute,
} as any)
const AppRumoursRoute = AppRumoursRouteImport.update({
  id: '/rumours',
  path: '/rumours',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai-analyst': typeof AppAiAnalystRoute
  '/analytics': typeof AppAnalyticsRoute
  '/clubs': typeof AppClubsRoute
  '/market': typeof AppMarketRoute
  '/my-club': typeof AppMyClubRoute
  '/players': typeof AppPlayersRoute
  '/rumours': typeof AppRumoursRoute
  '/settings': typeof AppSettingsRoute
  '/transfers': typeof AppTransfersRoute
  '/watchlist': typeof AppWatchlistRoute
}
export interface FileRoutesByTo {
  '/ai-analyst': typeof AppAiAnalystRoute
  '/analytics': typeof AppAnalyticsRoute
  '/clubs': typeof AppClubsRoute
  '/market': typeof AppMarketRoute
  '/my-club': typeof AppMyClubRoute
  '/players': typeof AppPlayersRoute
  '/rumours': typeof AppRumoursRoute
  '/settings': typeof AppSettingsRoute
  '/transfers': typeof AppTransfersRoute
  '/watchlist': typeof AppWatchlistRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-analyst': typeof AppAiAnalystRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/clubs': typeof AppClubsRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/my-club': typeof AppMyClubRoute
  '/_app/players': typeof AppPlayersRoute
  '/_app/rumours': typeof AppRumoursRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analyst'
    | '/analytics'
    | '/clubs'
    | '/market'
    | '/my-club'
    | '/players'
    | '/rumours'
    | '/settings'
    | '/transfers'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-analyst'
    | '/analytics'
    | '/clubs'
    | '/market'
    | '/my-club'
    | '/players'
    | '/rumours'
    | '/settings'
    | '/transfers'
    | '/watchlist'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ai-analyst'
    | '/_app/analytics'
    | '/_app/clubs'
    | '/_app/market'
    | '/_app/my-club'
    | '/_app/players'
    | '/_app/rumours'
    | '/_app/settings'
    | '/_app/transfers'
    | '/_app/watchlist'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-analyst': {
      id: '/_app/ai-analyst'
      path: '/ai-analyst'
      fullPath: '/ai-analyst'
      preLoaderRoute: typeof AppAiAnalystRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clubs': {
      id: '/_app/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AppClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-club': {
      id: '/_app/my-club'
      path: '/my-club'
      fullPath: '/my-club'
      preLoaderRoute: typeof AppMyClubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/players': {
      id: '/_app/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AppPlayersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rumours': {
      id: '/_app/rumours'
      path: '/rumours'
      fullPath: '/rumours'
      preLoaderRoute: typeof AppRumoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAnalystRoute: typeof AppAiAnalystRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClubsRoute: typeof AppClubsRoute
  AppMarketRoute: typeof AppMarketRoute
  AppMyClubRoute: typeof AppMyClubRoute
  AppPlayersRoute: typeof AppPlayersRoute
  AppRumoursRoute: typeof AppRumoursRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAnalystRoute: AppAiAnalystRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClubsRoute: AppClubsRoute,
  AppMarketRoute: AppMarketRoute,
  AppMyClubRoute: AppMyClubRoute,
  AppPlayersRoute: AppPlayersRoute,
  AppRumoursRoute: AppRumoursRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
